### ISSUE TITLE
Refactor common terraform workflows to use build-harness & pre-commit

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common-workflows#58]
As a product engineer we want to be able to write as much CI logic as possible to be tool agnostic. As such, despite some of the benefits of using a specific platforms' functionality for CI, we have decided to move the terraform workflow processes back to using make/precommit/build-harness as it is portable between CI systems, particularly github workflows and gitlab CI. The impact of this decision is that minimal platform specific scaffolding would be needed to adapt this process to a different CI tool.

Acceptance Criteria

```[tasklist]
### Tasks
- [ ] Create/update common workflow for terraform CI based on the work Andy Roth has done here: https://github.com/defenseunicorns/delivery-aws-iac/tree/main/.github
- [ ] Add the regula pre-commit hook as we had been using this in parallel to working with @CloudBeard on compliance
- [ ] Validate the auto-remediation of remediable checks as part of the workflow
- [ ] Update the terrafrom modules to use this common workflow
```
